Itcss structure
DeboraBSilva/trainee-landing-page pull request #1
Opened 2022-02-08 13:16 UTC by DeboraBSilva

Setting up colors and font variables. Using variable in css.

2022-02-08 13:33 UTC, DeboraBSilva commented
Page screenshot.
![image](https://user-images.githubusercontent.com/48605231/152997441-18b14c1a-9682-46e6-9ae3-60e071e3c1af.png)

2022-02-09 01:24 UTC, iagodahlem requested changes

2022-02-09 01:24 UTC, iagodahlem commented on src/styles/elements/_body.css
> +body{
💅

```suggestion
body {
```

2022-02-09 01:24 UTC, iagodahlem commented on src/styles/index.css
> +@import 'elements/_body.css';
Os imports tem que seguir a mesma ordem da pirâmide, então as settings sempre vem primeiro. Lembra do efeito cascata.

2022-02-09 01:24 UTC, iagodahlem commented on src/styles/elements/_body.css
> +}
É sempre bom já setar um padding: 0 no body também pra remover esse espaçamento default dos browsers.

2022-02-09 01:24 UTC, iagodahlem commented on src/styles/settings/_defaults.css
> +:root {
Pode deixar as variáveis todas num arquivo só, não precisa separar não. Pode ir tudo junto num settings.css ou algo assim.

2022-02-09 20:02 UTC, iagodahlem approved these changes

2022-02-10 12:02 UTC, merged